In [14]:
import numpy as np
arr=np.array([1,2,3])
print(arr)
print(arr.dtype)
print(type(arr))
print(arr.shape)

[1 2 3]
int32
<class 'numpy.ndarray'>
(3,)


In [15]:
import numpy as np
arr2d = np.array([[1,2, 3], [4,5,6]])
print(arr2d)
print(arr2d.dtype)
print(type(arr2d))
print(arr2d.shape)

[[1 2 3]
 [4 5 6]]
int32
<class 'numpy.ndarray'>
(2, 3)


In [11]:
import numpy as np
arr3d = np.array([[[1, 2, 3], [4,5,6]], [[7,8,9], [10, 11, 12]]])
print(arr3d)
print(arr3d.dtype)
print(type(arr3d))
print(arr3d.shape)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
int32
<class 'numpy.ndarray'>
(2, 2, 3)


In [23]:
# 1D Array
arr1d = np.array([1,2,3,4,5])
print(arr1d)
print(arr1d.shape)
print(type(arr1d))
print(arr1d[:])

[1 2 3 4 5]
(5,)
<class 'numpy.ndarray'>
[1 2 3 4 5]


In [29]:
# 2D Array
arr2d = np.array([[1,2,3,4], [5,6,7,8]])
print(arr2d)
print(type(arr2d))
print(arr2d.shape)
print(arr2d[1, 3])

[[1 2 3 4]
 [5 6 7 8]]
<class 'numpy.ndarray'>
(2, 4)
8


In [34]:
# arr3d
arr3d = np.array([[[1, 2, 3], [4,5,6]], [[7, 8, 9], [10,11,12]]])
print(arr3d)
print(type(arr3d))
print(arr3d.shape)
print(arr3d[1, 1, 2])

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
<class 'numpy.ndarray'>
(2, 2, 3)
12


In [ ]:
# NumPy Array Slicing

In [21]:
# 1D array slicing
import numpy as np
arr1d = np.array([1,2,3,4,5])
print(arr1d)
print(type(arr1d))
print(arr1d.dtype)
print(arr1d.shape)
print(arr1d[::2])

[1 2 3 4 5]
<class 'numpy.ndarray'>
int32
(5,)
[1 3 5]


In [55]:
# 2D array slicing
arr2d = np.array([[1,2,3,4], [5,6,7,8], [9, 10, 11, 12]])
print(arr2d)
print(type(arr2d))
print(arr2d.dtype)
print(arr2d.shape)
print(arr2d[0:3, 0:4:2])
#print(array_name[row_stat, row_end, start, end, step])
print(arr2d[0:3, 0:4:3])
print(arr2d[0:3, 1:3])
print(arr2d.ndim)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
<class 'numpy.ndarray'>
int32
(3, 4)
[[ 1  3]
 [ 5  7]
 [ 9 11]]
[[ 1  4]
 [ 5  8]
 [ 9 12]]
[[ 2  3]
 [ 6  7]
 [10 11]]
2


In [54]:
#3D Array slicing
arr3d = np.array([[[1,2,3,4],[5,6,7,8]], [[9,10,11,12],[13,14,15,16]], [[17,18,19,20],[21,22,23,24]]])
print(arr3d)
print(arr3d.dtype)
print(arr3d.shape)
print(type(arr3d))
print(arr3d[0:3, 0:3, 1:3])
print(arr3d[0:3, 0:3, 0:4])
print(arr3d[0:3, 0:3, 0:4:3])
print(arr3d.ndim)

[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [13 14 15 16]]

 [[17 18 19 20]
  [21 22 23 24]]]
int32
(3, 2, 4)
<class 'numpy.ndarray'>
[[[ 2  3]
  [ 6  7]]

 [[10 11]
  [14 15]]

 [[18 19]
  [22 23]]]
[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [13 14 15 16]]

 [[17 18 19 20]
  [21 22 23 24]]]
[[[ 1  4]
  [ 5  8]]

 [[ 9 12]
  [13 16]]

 [[17 20]
  [21 24]]]
3


In [66]:
#DataTypes in numpy
arr1 = np.array([True, False, True], dtype='b')
print(arr1.dtype)

int8


In [72]:
#Converting data type on existing array
#astype() => useful methods for vconverting data type, it creates a new array.
arr1 = np.array([1.5, 2.8, 3.6, 4.4])
newarr1 = arr1.astype('i')
print(newarr1)

arr2 = np.array([2, 5.5, 7, 8])
newarr2 = arr2.astype(float)
print(newarr2)

arr3 = np.array([1,2, 0, 5, 0])
newarr3 = arr3.astype(bool)
print(newarr3)

[1 2 3 4]
[2.  5.5 7.  8. ]
[ True  True False  True False]


In [80]:
#NumPy Copy Vs View
#Copy is a new array will nor affect original array.
#View is just the view of original array willaffect the original array.
arr1 = np.array([1, 2, 3, 4, 5])
copyarr = arr1.copy()
copyarr[0] = 10
arr2 = np.array([2, 4, 6, 8])
viewarr2 = arr2.view()
print(arr1)
print(copyarr)
print(arr2)
print(copyarr.base)
print(viewarr2.base)

[1 2 3 4 5]
[10  2  3  4  5]
[2 4 6 8]
None
[2 4 6 8]


In [93]:
#NumPy array reshaping
#Reshaping 1D array to 2D Array
arr1d = np.array([2,4,6,7,8,10, 12,13,14, 15, 17, 18])
print(arr1d)
print(arr1d.ndim)
print(arr1d.shape)
print(type(arr1d))
newarr = arr1d.reshape(3, 2, -1)
print(newarr)

[ 2  4  6  7  8 10 12 13 14 15 17 18]
1
(12,)
<class 'numpy.ndarray'>
[[[ 2  4]
  [ 6  7]]

 [[ 8 10]
  [12 13]]

 [[14 15]
  [17 18]]]


In [95]:
#Flattening the arrays (Converting multidimensional array to 1 Dimensional)
arr = np.array([[2,4,6,8], [10, 112, 14, 16]])
print(arr)
newarr = arr.reshape(-1)
print(newarr)

[[  2   4   6   8]
 [ 10 112  14  16]]
[  2   4   6   8  10 112  14  16]
